# Generated by Django 3.1.5 on 2021-01-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_auto_20210110_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='avialable',
            new_name='available',
        ),
    ]
